Implement upload agent
Artyom-Kitov/paketnik pull request #11
Opened 2024-10-31 05:02 UTC by g-vinokurov

2024-10-31 10:50 UTC, zpix1 commented on upload-agent/.gitignore
> -HELP.md
Я рекомендую обновлять gitignore по мере необходимости, особенно для питон проектов.

2024-10-31 10:50 UTC, zpix1 commented on upload-agent/test.py
> +from http.server import HTTPServer, BaseHTTPRequestHandler
может реальные тесты написать? насколько это сложно?

если будет мок сервер, то это будет полезно при написании реального бэка

2024-10-31 10:56 UTC, g-vinokurov commented on upload-agent/.gitignore
> -HELP.md
Да, согласен. Просто с текущего другого проекта шаблонный перенес. Стоит обновить?

2024-10-31 10:58 UTC, g-vinokurov commented on upload-agent/test.py
> +from http.server import HTTPServer, BaseHTTPRequestHandler
Немного не понял про мок сервер? Типа поднять его в тест-кейсе, отправить и загрузить на него файлы, потом брейкнуть в конце?

2024-10-31 11:31 UTC, g-vinokurov commented on upload-agent/test.py
> +from http.server import HTTPServer, BaseHTTPRequestHandler
Так, кажется чуть понял, что имеется в виду. Это он и есть, то что сейчас. Хочешь, чтобы тесты были в сервере?
Типа этого: https://habr.com/ru/companies/otus/articles/580896/ или этого https://github.com/ParentJA/example-mock-server-python, так?

2024-10-31 12:45 UTC, zpix1 commented on upload-agent/.gitignore
> -HELP.md
просто добавить все что нужно (пока нужно примерно ничего как я понимаю, __pycache__ только мб)

2024-10-31 12:52 UTC, zpix1 commented on upload-agent/test.py
> +from http.server import HTTPServer, BaseHTTPRequestHandler
Условно: поднимаешь и сервер и аплоадер в одном процессе, генерируешь фейковые файлы, загружаешь файлы на сервер (сервер их может запоминать или запоминать их хэши), смотришь что все файлы которые ты добавлял загрузились (с помощью unittest).

Короче, предлагаю сделать автотесты на загрузчик.

2024-10-31 13:32 UTC, g-vinokurov commented on upload-agent/.gitignore
> -HELP.md
Там есть всё, что обычно не требуется (pycache, venv, .env и т.п.). То есть убрать лишнее?

2024-10-31 13:32 UTC, g-vinokurov commented on upload-agent/test.py
> +from http.server import HTTPServer, BaseHTTPRequestHandler
Понял

2024-11-07 13:48 UTC, sescer requested changes
Также если пишешь typehint, то можно и на возвращаемое значение тоже

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +        self._load()
можем обработать заранее если нет такого filepath

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +
новая линия нужна после прогресса?

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +        response = requests.post(url, data=upload_in_chunks(path_to_pcap), headers=headers)
сразу лучше задать timeout явно

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +    pcaps = sorted(pcaps, key=lambda x: datetime.datetime.fromtimestamp(os.path.getmtime(x)))
а с stat не получилось или не пробовал? Типо так:
`sorted(src_dir.glob('*.pcap'), key=lambda x: x.stat().st_mtime)`

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +    src_dir = pathlib.Path(src_dir)
можно добавить resolve()

2024-11-07 13:48 UTC, sescer commented on upload-agent/main.py
> +    storage = PcapsStorage('.storage.txt')
лучше вынести в константу название файлика

2024-11-07 13:56 UTC, g-vinokurov commented on upload-agent/main.py
> +
Нет, иначе он в одну строчку не может выводить этот прогресс. Там всё ок. После загрузки следующий текст с новой строки.

2024-11-07 13:57 UTC, g-vinokurov commented on upload-agent/main.py
> +        response = requests.post(url, data=upload_in_chunks(path_to_pcap), headers=headers)
Согласен

2024-11-07 13:57 UTC, g-vinokurov commented on upload-agent/main.py
> +    pcaps = sorted(pcaps, key=lambda x: datetime.datetime.fromtimestamp(os.path.getmtime(x)))
Ну, можно. Но вроде это одно и тоже. Вот с датой создания, да, там есть разница (на linux и windows)

2024-11-07 13:59 UTC, g-vinokurov commented on upload-agent/main.py
> +    src_dir = pathlib.Path(src_dir)
Для симлинков?)

2024-11-07 13:59 UTC, g-vinokurov commented on upload-agent/main.py
> +    storage = PcapsStorage('.storage.txt')
Да, подправлю

2024-11-07 14:03 UTC, g-vinokurov commented on upload-agent/main.py
> +        self._load()
То есть вынести проверку из load в init?

2024-11-11 11:15 UTC, sescer approved these changes

2024-11-11 11:29 UTC, merged