PAKETNIK-12993: add some auto tests for upload agent
Artyom-Kitov/paketnik pull request #23
Opened 2024-11-14 08:39 UTC by vladstepanyuk

2024-11-14 10:39 UTC, d-makogon commented on upload-agent/test.py
> +def get_scipt_name() -> str:
```suggestion
def get_script_name() -> str:
```

2024-11-14 10:39 UTC, d-makogon commented on upload-agent/test.py
> +    return os.path.abspath("./" + TEST_DATA_DIR + "/" + filename)
получается этот скрипт надо только из его директории запускать, можно сделать так:
```suggestion
SCRIPT_PATH = os.path.realpath(__file__)
SCRIPT_DIR = os.path.dirname(cur_script)
 
 def ...
    return os.path.abspath(SCRIPT_DIR + TEST_DATA_DIR + "/" + filename)
```

2024-11-14 10:39 UTC, d-makogon commented on upload-agent/test.py
> +    recieved_data = set()
```suggestion
    received_data = set()
```

2024-11-14 10:39 UTC, d-makogon commented on upload-agent/test.py
> +        return MockHTTPRequestHandler.recieved_data.copy()
Зачем copy? Везде где юзается вроде не нужна копия

2024-11-14 10:48 UTC, d-makogon commented on upload-agent/test.py
> +        p.wait()
Это неверно. Нужно юзать `p.kill()`

2024-11-14 10:48 UTC, d-makogon commented on upload-agent/test.py
> +        os.mkdir(TEST_DIR)
А если уже есть такая папка? Что будет вообще? Вроде должен exception вылететь
Она может быть после прошлого запуска, который упал посреди теста (может такое быть? tearDown же не зовется при исключении?)
Может, юзать [TemporaryDirectory](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory):
```
setUp:
  temp_dir = tempfile.TemporaryDirectory()


use:
   print(temp_dir.name)

tearDown:
   temp_dir.cleanup()

```

2024-11-14 11:05 UTC, d-makogon commented
Можно было использовать новый python pathlib вместо работы с путями как со строками 
Ну это если интересно, и так ок

2024-11-14 11:08 UTC, d-makogon commented
Проапдейти плиз по замечаниям к тест кейсам из https://ai.nsu.ru/issues/13235

2024-11-14 11:20 UTC, d-makogon commented on upload-agent/test.py
> +        )
Это довольно часто встречается, вынеси в функцию
```suggestion
     def copy_test_file(filename):
        shutil.copyfile(
            get_filepath_in_test_data_dir(filename),
            get_filepath_in_directory_for_testing(filename),
        )
```

2024-11-14 11:20 UTC, d-makogon commented on upload-agent/test.py
> +        self.thread.start()
Сделай здесь
```suggestion
        self.thread.start()
        self.file_1_correct = get_filepath_in_test_data_dir(TEST_FILE_1_CORRECT)
        self.file_2_correct = get_filepath_in_test_data_dir(TEST_FILE_2_CORRECT)
        self.file_3_correct = get_filepath_in_test_data_dir(TEST_FILE_3_CORRECT)
```

и потом юзай уже эти поля, чтобы не засорять код

2024-11-14 11:22 UTC, d-makogon commented on upload-agent/test.py
> +def get_filepath_in_test_data_dir(filename: str) -> str:
Длинные названия, сделай короче. типа такого
```suggestion
def test_file_path(filename: str) -> str:
```

2024-11-14 11:22 UTC, d-makogon commented on upload-agent/test.py
> +def get_filepath_in_directory_for_testing(filename: str) -> str:
```suggestion
def testdir_file_path(filename: str) -> str:
```

2024-11-14 11:25 UTC, d-makogon requested changes

2024-11-14 11:25 UTC, d-makogon commented on upload-agent/test.py
> +        self.thread.start()
Здесь нужна какая-то проверка, что http сервер запустился и готов принимать соединения.

2024-11-14 11:25 UTC, d-makogon commented on upload-agent/test.py
> +        httpd.shutdown()
Лучше использовтаь `httpd.server_close()` после shutdown.

2024-11-14 11:25 UTC, d-makogon commented on upload-agent/test.py
> +        p.wait()
Это везде нужно поменять

И думаю нужно  проверять код возврата процесса. И падать в тесте, если он неожиданный

2024-11-14 11:25 UTC, d-makogon commented on upload-agent/test.py
> +STANDART_TIMEOUT = 1.5
```suggestion
STANDARD_TIMEOUT = 1.5
```

2024-11-20 14:29 UTC, vladstepanyuk commented on upload-agent/test.py
> +        p.wait()
почему p.kill()? Корректное завершение работы в скрипте сейчас происходит при получении  эксепшена KeyboardInterrupt, который и соответствует сигналу signal.SIGINT. Да и если делать через килл то скрипт завершается с ненулевым кодом возврата, что, как понимаю, не ожидается.
https://github.com/Artyom-Kitov/paketnik/blob/8a47315bd8470c763ea6db1a2c1b22060829b1f3/upload-agent/main.py#L159-L165

2024-11-20 14:55 UTC, vladstepanyuk commented on upload-agent/test.py
> +    return os.path.abspath("./" + TEST_DATA_DIR + "/" + filename)
Поскольку папка test_data лежит не в папке со скриптом, тесты запускаются из корня проекта. Тут либо перенести test_data к скрипту в папку upload-agent (что мне кажется нелогично, так как тестовые данные не только для тестов upload agent понадобятся), либо прописывать переходы назад по директориям, но зачем это делать, запуск из корня проекта выглядит вполне себе ок

2024-11-20 15:48 UTC, vladstepanyuk commented
> Проапдейти плиз по замечаниям к тест кейсам из https://ai.nsu.ru/issues/13235

Добавить проверку аутпута теста?

2024-11-24 19:47 UTC, d-makogon approved these changes

2024-11-28 14:14 UTC, merged