Pakentik 12791 linters configuration
Artyom-Kitov/paketnik pull request #6
Opened 2024-10-23 09:20 UTC by DmitryStonie

Init eslint, install prettier, add rules for auto-formating.

2024-10-23 13:35 UTC, zpix1 commented on frontend/.prettierignore
> +coverage
coverage? у нас есть это?

2024-10-23 13:36 UTC, zpix1 commented on frontend/.prettierrc
> +{
нужно отлинтить сам проект, и отформатить. 

также добавить script lint:fix который автофиксит в package.json

2024-10-23 13:46 UTC, zpix1 requested changes
Отформатить проект линтером, json файлы тоже лучше задеть.

Ну и в названии ветки опечатка, лучше не допускать такого, но тут уже менять не нужно :)

2024-10-23 15:16 UTC, DmitryStonie commented on frontend/.prettierignore
> +coverage
нет, убрал

2024-10-23 15:19 UTC, DmitryStonie commented on frontend/.prettierrc
> +{
Отлинтил, отформатил. Добавил скрипт lint:fix (делает eslint --fix .) и format (делает prettier --write .), добавил js в конфиг eslint
Не понравилось, что при линте 600+ ошибок (в основном, в файле paketnik\frontend\dist\assets\index-f40OySzR.js)

2024-10-23 15:31 UTC, zpix1 commented on frontend/.prettierrc
> +{
ну dist, конечно, нужно исключить из линта.

2024-10-23 15:31 UTC, zpix1 commented
И еще нужно ребейзнуться и заново прогнать линт :)

2024-10-23 16:35 UTC, DmitryStonie commented on frontend/.prettierrc
> +{
Убрал

2024-10-23 16:37 UTC, DmitryStonie commented
Сделал rebase. При этом, так как делал в первый раз, часть строчек дублировались. Убрал их. Отлинтил и отформатировал. Попробовал запустить - не заработало. После установки tailwindcss все заработало.

2024-10-24 13:57 UTC, zpix1 commented on frontend/index.html
> +    <title>Paketnik</title>
а почему показывает этот чендж, надпись пакетник же уже в мастере? как будто ребейз прошел как-то не так

2024-10-24 14:09 UTC, DmitryStonie commented on frontend/index.html
> +    <title>Paketnik</title>
я могу откатить rebase и сделать его заново?

2024-10-24 14:20 UTC, zpix1 commented on frontend/index.html
> +    <title>Paketnik</title>
да, софт ресет на мастер и новый коммит)

2024-10-25 13:55 UTC, DmitryStonie commented
Получилось. Повторов не нашел. Правда, сделано это все через одно место... но я и не умею нормально

2024-10-26 08:18 UTC, DmitryStonie commented
Я предлагаю выкинуть эту ветку. Я сделал новую с названием PAKETNIK-12791-linters-configuration (исправлена ошибка), она получена в результате rebase из нужного коммита в ветке PAKETNIK-12791-linters-configuration. На первом фото то, что я наделал в предыдущей ветке.
![image](https://github.com/user-attachments/assets/54844d32-3e3b-42fe-a54c-f6d9db8c5156)
На втором фото новая ветка, которую я предлагаю.
![image](https://github.com/user-attachments/assets/8a7d2ef2-f6aa-4899-8f96-8ae3b0752699)
В итоге, в master не будет мусора.

2024-10-30 12:49 UTC, closed without merging